Django/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name="home"),
    path('<int:post_id>/', views.post, name="post"),
    path('exemplo/', views.exemplo, name="exemplo"),
]

Django/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

Django/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

Django/blog/models.py
from django.db import models

# Create your models here.

Django/blog/views.py
from typing import Any

from django.http import Http404, HttpRequest
from django.shortcuts import render
from blog.data import posts

# Create your views here.

def blog(request):
    print('blog')

    context = {
        'posts': posts,
    }

    return render(
        request,
        'blog/index.html',
        context
    )

def post(request:HttpRequest, post_id:int):
    found_post:dict[str,Any] | None = None

    for post in posts:
        if post["id"] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404("Post não existe.")

    context = {
        'post': found_post,
        'title': found_post['title'] + ' - '
    }

    return render(
        request,
        'blog/post.html',
        context
    )


def exemplo(request):
    print('exemplo')

    context = {
        'title': 'Essa é uma página de exemplo - ',
    }

    return render(
        request,
        'blog/exemplo.html',
        context
    )

Django/home/views.py
from django.shortcuts import render
def home(request):
    print('home')
    return render(
        request,
        "home/index.html",
        {
            "text" : "Estamos na home",
        }
    )

Django/blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} 
  {{ text }}
{% endblock texto %}

Django/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% if text %}
  {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
  {% for post in posts %}
    {% include 'global/partials/post_block.html' %}
  {% endfor %}
{% endblock posts %}

Django/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% if text %}
  {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
  <article class="post single-post">
    <header>
        <h2 class="post__title">
            <a href= " {% url "blog:post" post.id %}">
                {{ post.title }}
            </a>
        </h2>
    </header>
    <div class="post__body">{{ post.body }}</div>
  </article>

{% endblock posts %}

Django/home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOME HTML</h1>
</body>
</html>

Django/home/templates/home/index.html
{% extends 'global/base.html' %}

{% if text %}
  {% block texto %} {{ text }} {% endblock texto %}
{% endif %}